//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string AccountTitle {
            get {
                return ResourceManager.GetString("AccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch.
        /// </summary>
        public static string Batch {
            get {
                return ResourceManager.GetString("Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batches.
        /// </summary>
        public static string Batches {
            get {
                return ResourceManager.GetString("Batches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thinking....
        /// </summary>
        public static string Bot_Thinking {
            get {
                return ResourceManager.GetString("Bot_Thinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to DMS Lite!.
        /// </summary>
        public static string Bot_Welcome1 {
            get {
                return ResourceManager.GetString("Bot_Welcome1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can always type help if you are feeling stuck!.
        /// </summary>
        public static string Bot_Welcome2 {
            get {
                return ResourceManager.GetString("Bot_Welcome2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to do?.
        /// </summary>
        public static string Bot_Welcome3 {
            get {
                return ResourceManager.GetString("Bot_Welcome3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Closed.
        /// </summary>
        public static string CloseDate {
            get {
                return ResourceManager.GetString("CloseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string ConfirmPassError {
            get {
                return ResourceManager.GetString("ConfirmPassError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Donations.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Created.
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBA.
        /// </summary>
        public static string DBA {
            get {
                return ResourceManager.GetString("DBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string DonAddress {
            get {
                return ResourceManager.GetString("DonAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string DonationAccount {
            get {
                return ResourceManager.GetString("DonationAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch.
        /// </summary>
        public static string DonationBatch {
            get {
                return ResourceManager.GetString("DonationBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donor.
        /// </summary>
        public static string DonationDonor {
            get {
                return ResourceManager.GetString("DonationDonor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt.
        /// </summary>
        public static string DonationReceipt {
            get {
                return ResourceManager.GetString("DonationReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donor ID.
        /// </summary>
        public static string DonorID {
            get {
                return ResourceManager.GetString("DonorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donors.
        /// </summary>
        public static string Donors {
            get {
                return ResourceManager.GetString("Donors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Donor.
        /// </summary>
        public static string NewDonor {
            get {
                return ResourceManager.GetString("NewDonor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ObjectDescription {
            get {
                return ResourceManager.GetString("ObjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Address.
        /// </summary>
        public static string OrgAddress {
            get {
                return ResourceManager.GetString("OrgAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Name.
        /// </summary>
        public static string OrgName {
            get {
                return ResourceManager.GetString("OrgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Frequency.
        /// </summary>
        public static string ReceiptFrequency {
            get {
                return ResourceManager.GetString("ReceiptFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Number.
        /// </summary>
        public static string RegistrationNumer {
            get {
                return ResourceManager.GetString("RegistrationNumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember This Browser?.
        /// </summary>
        public static string RememberBrowser {
            get {
                return ResourceManager.GetString("RememberBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similar Donors.
        /// </summary>
        public static string SimilarDonors {
            get {
                return ResourceManager.GetString("SimilarDonors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount Donated.
        /// </summary>
        public static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string UI_Account {
            get {
                return ResourceManager.GetString("UI_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string UI_Add {
            get {
                return ResourceManager.GetString("UI_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Another Batch.
        /// </summary>
        public static string UI_AddAnoBatch {
            get {
                return ResourceManager.GetString("UI_AddAnoBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a New Batch.
        /// </summary>
        public static string UI_AddBatch {
            get {
                return ResourceManager.GetString("UI_AddBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added New Batch.
        /// </summary>
        public static string UI_AddBatchSuc {
            get {
                return ResourceManager.GetString("UI_AddBatchSuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add one?.
        /// </summary>
        public static string UI_AddOne {
            get {
                return ResourceManager.GetString("UI_AddOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch ID.
        /// </summary>
        public static string UI_BatchID {
            get {
                return ResourceManager.GetString("UI_BatchID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string UI_Cancel {
            get {
                return ResourceManager.GetString("UI_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to reset your password..
        /// </summary>
        public static string UI_CheckEmail {
            get {
                return ResourceManager.GetString("UI_CheckEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to Log in.
        /// </summary>
        public static string UI_ClickLogin {
            get {
                return ResourceManager.GetString("UI_ClickLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string UI_Close {
            get {
                return ResourceManager.GetString("UI_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close A Batch.
        /// </summary>
        public static string UI_CloseBatch {
            get {
                return ResourceManager.GetString("UI_CloseBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close This Batch.
        /// </summary>
        public static string UI_CloseThisBatch {
            get {
                return ResourceManager.GetString("UI_CloseThisBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        public static string UI_ConfirmEmail {
            get {
                return ResourceManager.GetString("UI_ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your email. Please.
        /// </summary>
        public static string UI_ConfirmThanks {
            get {
                return ResourceManager.GetString("UI_ConfirmThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account..
        /// </summary>
        public static string UI_CreateNewAccount {
            get {
                return ResourceManager.GetString("UI_CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has no donations. Would you like to.
        /// </summary>
        public static string UI_DonWouldYouLikeTo {
            get {
                return ResourceManager.GetString("UI_DonWouldYouLikeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Link.
        /// </summary>
        public static string UI_EmailLink {
            get {
                return ResourceManager.GetString("UI_EmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email..
        /// </summary>
        public static string UI_EnterEmail {
            get {
                return ResourceManager.GetString("UI_EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter verification code.
        /// </summary>
        public static string UI_EnterVerCode {
            get {
                return ResourceManager.GetString("UI_EnterVerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string UI_ForgotPassword {
            get {
                return ResourceManager.GetString("UI_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password Confirmation.
        /// </summary>
        public static string UI_ForgotPasswordConfirmation {
            get {
                return ResourceManager.GetString("UI_ForgotPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has been closed..
        /// </summary>
        public static string UI_HasBeenClosed {
            get {
                return ResourceManager.GetString("UI_HasBeenClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did something break?.
        /// </summary>
        public static string UI_HelpButton {
            get {
                return ResourceManager.GetString("UI_HelpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string UI_HomeTitle {
            get {
                return ResourceManager.GetString("UI_HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string UI_Id {
            get {
                return ResourceManager.GetString("UI_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string UI_LogIn {
            get {
                return ResourceManager.GetString("UI_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string UI_Name {
            get {
                return ResourceManager.GetString("UI_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizations.
        /// </summary>
        public static string UI_Organizations {
            get {
                return ResourceManager.GetString("UI_Organizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string UI_Register {
            get {
                return ResourceManager.GetString("UI_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string UI_Reset {
            get {
                return ResourceManager.GetString("UI_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset. Please.
        /// </summary>
        public static string UI_ResetConfirm {
            get {
                return ResourceManager.GetString("UI_ResetConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string UI_ResetPassword {
            get {
                return ResourceManager.GetString("UI_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password confirmation.
        /// </summary>
        public static string UI_ResetPasswordConfirmation {
            get {
                return ResourceManager.GetString("UI_ResetPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password..
        /// </summary>
        public static string UI_ResetYourPass {
            get {
                return ResourceManager.GetString("UI_ResetYourPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Two-Factor Authentication Provider:.
        /// </summary>
        public static string UI_Select2FAuthProvider {
            get {
                return ResourceManager.GetString("UI_Select2FAuthProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Organization.
        /// </summary>
        public static string UI_SelectOrg {
            get {
                return ResourceManager.GetString("UI_SelectOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string UI_Send {
            get {
                return ResourceManager.GetString("UI_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string UI_Submit {
            get {
                return ResourceManager.GetString("UI_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The batch.
        /// </summary>
        public static string UI_TheBatch {
            get {
                return ResourceManager.GetString("UI_TheBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now showing both posted and open batches!.
        /// </summary>
        public static string UI_ToggleAllBatches {
            get {
                return ResourceManager.GetString("UI_ToggleAllBatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now only showing open batches!.
        /// </summary>
        public static string UI_ToggleOpenBatches {
            get {
                return ResourceManager.GetString("UI_ToggleOpenBatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string UI_Verify {
            get {
                return ResourceManager.GetString("UI_Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
