// <auto-generated />
namespace DMSLite.DataContexts.IdentityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GlobalTenantUserFilter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GlobalTenantUserFilter));
        
        string IMigrationMetadata.Id
        {
            get { return "201611151908267_GlobalTenantUserFilter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
